import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/providers/tanstack-provider";
import { Toaster } from "sonner";

const nunito = Nunito({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Gradma Meals",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pr-BR">
      <body
        className={`${nunito.className} antialiased`}
      >
        <TanstackProvider>
          {children}
          <Toaster/>
        </TanstackProvider>
      </body>
    </html>
  );
}
